config/routes.rb
Rails.application.routes.draw do
  
  resources :gift_registries do
    collection do
      get "create_empty_record"
      post "gift_registries_table"
      delete "delete" 
      
    end
  end
  
  resources :brides do
    collection do

      get "create_empty_record"
      post "bride_table"
      delete "delete" 
      post "update_gift_list"
      post "render_gift_section"
      post "update_gift_order"
      post "render_gift_list"
    end
  end
  
  resources :order_management do
    collection do
      get 'order_page'
      post 'add_to_order'
      get 'complete_order'
      put 'update_cart_item'
      post 'complete_order'
      get 'complete_order'
      post 'enter_order'
      get 'enter_order'
      get 'get_product_sub_totals'
      get 'delete_cart_item'
      get 'get_cart_contents'
    end
  end
  
  match "/site/show_my_gifts" => "site#show_my_gifts", via: :get
  match "/site/show_gifts" => "site#show_gifts", via: :get
  match "/site/update_cart_item" => "site#update_cart_item", via: :put
  match "/site/update_session" => "site#update_session", via: :put
  match "/site/find_bride" => "site#find_bride", via: :get
  match "/site/bride_active" => "site#bride_active", via: :get

  
end

app/models/bride.rb
class Bride < ActiveRecord::Base
  belongs_to :user
  has_many :gift_registries
  has_many :order_items
  has_many :orders

end

app/controllers/brides_controller.rb
class BridesController < ApplicationController
  before_action :set_bride, only: [:show, :edit, :update, :destroy, :update_gift_list, :render_gift_section, :render_gift_list]

  # GET /brides
  def index
    @brides = Bride.all
  end

  # GET /brides/1
  #
  #
  
  def show
  end

  # GET /brides/new
  def new
    @bride = Bride.new
  end

  # GET /brides/1/edit
  def edit
  end

  # POST /brides
  def create
    @bride = Bride.new(bride_params)

    if @bride.save
      redirect_to @bride, notice: 'Bride was successfully created.'
    else
      render :new
    end
  end
  
  
  # POST /brides
   
  def create_empty_record
    @bride = Bride.new
    
    @bride.user = User.new
    @bride.user.name = "User_" + Time.now.to_i.to_s + "@someaddress.com"
    @bride.user.password = "password"
    @bride.user.password_confirmation = "password"
 
    role = Role.find_by_name("Bride")
    @bride.user.roles << role
    
    @bride.user.user_attribute = UserAttribute.new
    @bride.user.user_attribute.first_name = "First"
    @bride.user.user_attribute.last_name = "Last"
    @bride.user.user_attribute.save
    
    @bride.user.save
    
    @bride.save
    
    redirect_to @bride, notice: 'Bride was successfully created with password: "password"'
  end


  # PATCH/PUT /brides/1
  #  def update
  #    if @bride.update(bride_params)
  #      redirect_to @bride, notice: 'Bride was successfully updated.'
  #    else
  #      render :edit
  #    end
  #  end

  def update
    respond_to do |format|
      if @bride.update(bride_params)
        format.html { redirect_to(:action =>"edit", :notice => 'Bride was successfully updated.') }
        format.json { render :json=> {:notice => 'Bride was successfully updated.'} }
      else
        format.html { render :action => "edit" }
        format.json  { render :json => @bride.errors, :status => :unprocessable_entity }
      end
    end
  end
  
  # DELETE /coupons/1
  # DELETE /coupons/1.json
  def destroy
    @bride.destroy

    respond_to do |format|
      format.html { redirect_to brides_url, notice: 'Bride was successfully deleted.' }
      format.json { head :ok }
    end
  end
  
    

  def update_gift_list
    @product = Product.find(params[:product_id])

    check_for_duplicate = GiftRegistry.where(:product_id=>params[:product_id]).where(:bride_id=>params[:id])
    if check_for_duplicate.length == 0 then
      @gift_product = GiftRegistry.new
      @gift_product.product_id=params[:product_id]
      @gift_product.quantity_reserved = 0
      @gift_product.quantity_requested = 0
      @gift_product.position = 999
      @gift_product.save
      @bride.gift_registries << @gift_product
      @bride.save
      render :json=>{:success=>true, :alert=>"Gift '" + @gift_product.product.product_name.to_s + "' added to this bride."} 
    else
      render :json=>{:success=>false, :alert=>"Can not add duplicate gift."} 

    end
    
  end
  
  def render_gift_section
  
    render(partial: "gift_section")
    
  end
  
    def render_gift_list
    @gifts = @bride.gift_registries
    
    render(partial: "gift_list")
   
  end
    
  def update_gift_order
    params[:gift].each_with_index do |id, position|
      #     related_product = ProductRelatedProduct.find(id)
      #     related_product.position = position
      #     related_product.save
      #   Image.update(id, :position => position)
      GiftRegistry.reorder(id,position)
    end
    render nothing: true

  end

  
  
  def bride_table
    @objects = current_objects(params)
    @total_objects = total_objects(params)
    render layout: false
  end
  
    
  
  private
  
  
  def current_objects(params={})
    current_page = (params[:start].to_i/params[:length].to_i rescue 0)+1
    @current_objects = Bride.eager_load(:user).eager_load(:user=>:user_attribute).page(current_page).per(params[:length]). 
      order("#{datatable_columns(params[:order]["0"][:column])} #{params[:order]["0"][:dir] || "DESC"}").
      where(conditions)
  end
    

  def total_objects(params={})
    @total_objects = Bride.count
  end

  def datatable_columns(column_id)
    case column_id.to_i
    when 0
      return "brides.id"
    when 1
      return "user_attributes.first_name"
    else
      return "brides.wedding_date"
    end
  end

  def conditions
    conditions = []
    conditions << "( `user_attributes`.`first_name` LIKE '%#{params[:search][:value]}%') OR (`user_attributes`.`last_name` LIKE '%#{params[:search][:value]}%') OR ( `brides`.`wedding_date` LIKE '%#{params[:search][:value]}%')" if (!params[:search][:value].blank?)
    return conditions.join(" AND ")
  end
  
  # Use callbacks to share common setup or constraints between actions.
  def set_bride
    @bride = Bride.find(params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def bride_params
    params.require(:bride).permit(:id, :user_id, :wedding_date, :groom_full_name)
  end
end

app/helpers/brides_helper.rb
module BridesHelper


def bride_info(bride)
    returnval = "<div id=\"attr-bride\" class=\"hidden-item\">"
    returnval << "<div id=\"bride-id\">"+(bride.id.to_s rescue "-1")+"</div>"
    returnval << "<div id=\"user-id\">"+(bride.user.id.to_s rescue "-1")+"</div>"
    
    returnval=returnval + "</div>"
    return returnval.html_safe
 
  end
  
  def bride_edit_div(bride)
    returnval=""
    if session[:user_id] then
      user=User.find(session[:user_id])
      if user.roles.detect{|role|((role.name=="Admin") | (role.name=="Site Owner"))} then
        returnval="<div id=\"edit-bride-gear\" class=\"edit-bride-gear\">"
        returnval << "<div id='bride-id' class='hidden-item'>#{bride.id}</div>"
        returnval=returnval+image_tag("interface/edit.png",:border=>"0", :class=>"imagebutton", :title => "Edit this Bride")
        returnval=returnval + "</div>"

      end
    end
    return returnval.html_safe
  end
  
  def bride_active
    returnval="false"
    if session[:user_id] then
      user=User.find(session[:user_id])
      if user.roles.detect{|role|(role.name=="Bride")} then
        returnval="true"
      end
    end
    return returnval.html_safe
  end

end

  

app/views/brides/_bride_data_table.html.erb
<table width="100%" cellpadding="0" cellspacing="0" border="0" class="display" id="bride-table">
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Wedding Date</th>
      <th>-</th>
    </tr>
  </thead>
  <tbody>

  </tbody>
  <tfoot>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Wedding Date</th>
      <th>--</th>
    </tr>
  </tfoot>
</table>

app/views/brides/_form.html.erb
<p>
    <b>First Name:</b><br>
    <%=editablefieldcreate("first_name", @bride.user.user_attribute)%>
</p>

<p>
    <b>Last Name:</b><br>
    <%=editablefieldcreate("last_name", @bride.user.user_attribute)%>
</p>

<p>
    <b>Email Address:</b><br>
    <%=editablefieldcreate("name", @bride.user)%>
</p>

<p>
    <b>Password Management:</b><br>
<div class="button-link" id="password-user-item">Change Password</div>
<br>    
</p>

<p>
    <b>Wedding Date:</b><br>
    <%=editabledatefieldcreate("wedding_date", @bride ,"01/01/2001", {:format_type=>"date", :format_string=>"%m/%d/%Y"})%>
</p>

<p>
    <b>Groom Full Name:</b><br>
    <%=editablefieldcreate("groom_full_name", @bride)%>
</p>


<%#= form_for(@bride) do |f| %>
<%# if @bride.errors.any? %>
<%#*<div id="error_explanation">%>
<%#*<h2><%= pluralize(@bride.errors.count, "error") % > prohibited this bride from being saved:</h2>%>

<%#*<ul>%>
<%# @bride.errors.full_messages.each do |message| %>
<%#*<li><%= message % ></li>%>
<%# end %>
<%#*</ul>%>
<%#*</div>%>
<%# end %>

<%#*<div class="field">%>
<%#= f.label :id % ><br>
<%#= f.number_field :id %>
<%#*</div>%>
<%#*<div class="field">%>
<%#= f.label :user_id % ><br>
<%#= f.number_field :user_id %>
<%#*</div>%>
<%#*<div class="field">%>
<%#= f.label :wedding_date % ><br>
<%#= f.date_select :wedding_date %>
<%#*</div>%>
<%#*<div class="field">%>
<%#= f.label :groom_full_name % ><br>
<%#= f.text_field :groom_full_name %>
<%#*</div>%>
<%#*<div class="actions">%>
<%#= f.submit %>
<%#*</div>%>
<%# end %>

app/views/brides/_gift_list.html.erb
<%# return if (not defined?(picture_list).nil?) %>
<% @gifts = gift_list if @gifts.blank? %>
<%= hidden_div_if((@gifts.empty?) , :id=>"gift-products") %>

<% @gifts.order(:position).each do |gift| %>
  <% puts("---------->  gift.product: '#{gift.product.product_name}'") %>
  <%= render(:partial=>"gift_view.html" , :locals=>{:gift=>gift})%>
<% end if not @gifts.blank?%>

<%="</div>".html_safe if !@gifts.empty? %>

app/views/brides/_gift_section.html.erb
<div id="product-search-bar">
                      Add Products: <input id="product-search" />
                   <%= link_to 'New Product', {:action=>:create_empty_record,:controller=>:gift_registries, :typeofrecord=>"product", :bride_id=>@bride.id}, :class=>"button-link",:id=>"new-product", :remote=>true%>


</div>
<div id="gift-section" class="giftsection back-office-refresh-element" data-update="updateGiftList">
                 
    
          <%#= hidden_div_if((@bride.gift_registries.empty?) , :id=>"gift-products") %>

          <%= render(:partial => "gift_list", :object => @bride.gift_registries) %>
          

          <%#="</div>".html_safe %>

      </div> 

app/views/brides/_gift_view.html.erb
<%gift=@gift if gift.blank?%>

<div id="gift_<%=gift.id.to_s%>" data-id='product_<%=gift.id.to_s%>' class="product-list-item">
    <div class="product-delete-icon ui-icon ui-icon-closethick">
        <%= link_to('X',gift, {method: :delete, remote: true, data: { confirm: "Are you sure?" }, class: 'gift-delete'})%>
      </div> 
      <div class="gift-product-item"> 

          <div class="product-title"><%=truncate(gift.product.product_name, length: 12) rescue "product not found"%> 

          </div>
      </div> 

      <div class="product-block">
          <div class="gift-item">
              <%=  product_edit_div(gift.product)%>
              <div class="gift-float-center">
                  <%= image_tag(gift.product.pictures[0].blank? ? "empty_s.jpg" : gift.product.pictures[0].image_url(:product_list).to_s,:class=>"product-image") rescue "" %>
              </div>
              <b>Requested:</b>
              <%=editablefieldcreate("quantity_requested", gift)%>
              <br>
              <b>Reserved:</b>
              <%#=editablefieldcreate("quantity_reserved", gift)%>
              <div id="quantity_reserved"> <%=gift.true_quantity_reserved%></div>
          </div>       
      </div>

  </div> 

app/views/brides/bride_table.json.erb
{"draw": <%= params[:draw] || -1 %>,
 "recordsTotal": <%= @total_objects %>,
 "recordsFiltered": <%= @total_objects %>,
 "data":[
<% @objects.each do |bride| %>
  [
   "<%= bride.id%><div id='bride-id' class='hidden-item'><%=bride.id%></div> ",
   "<%= bride.user.user_attribute.first_name rescue "" %> <%= bride.user.user_attribute.last_name rescue "" %>",
   "<%= bride.wedding_date rescue "n/a" %>",  
   "<center><div class='delete-bride-item'><%=image_tag('interface/delete.png', :border=>'0').gsub("\"", "'").html_safe() %></div> </center>"
  ] <% if @objects.last != bride then %> , <% end %>
<% end %>
]}

app/views/brides/edit.html.erb
<div class="hidden-item">
    <div id="as_window"><%=params[:request_type]=="window"%></div>
    <div id="dialog-height">650</div>
    <div id="dialog-width">1050</div>
    <div id="dialog-name">Edit Bride (<%=@bride.user.user_attribute.first_name%> <%=@bride.user.user_attribute.last_name%> )</div>
</div>

<%=  bride_info(@bride) %>

<div id="bride-tabs">
    <ul>
        <li><a href="#information-tab">Information</a></li>
        <li><a href="#products-tab">Products</a></li>
    </ul>
    <div id="information-tab">
        <div class="cms-content">
            <%= render 'form' %>
        </div>
    </div>

    <div id="products-tab">
        <div class="cms-content">
            <div id="product-gift">
                <%= render :partial=>"gift_section" %>
            </div>
        </div>
    </div>
</div>

app/views/brides/index.html.erb
<div class="hidden-item">
    <div id="as_window"><%=params[:request_type]=="window"%></div>
    <div id="dialog-height">650</div>
    <div id="dialog-width">1050</div>
    <div id="dialog-name">Bride Manager</div>
</div>

<%=page_attr_display(nil,"true") %>

<div class="cms-block">
  <div align="center">
    <!-- START:flash -->
    <% if flash[:notice] -%>
      <div id="notice"><%= flash[:notice] %></div>
    <% end -%>
    <!-- END:flash -->
  </div>

  <div id="site-pref-list">
   <!-- <h1  class="cms-header">Site Brides</h1> -->

     <%=link_to 'New Bride',{ :action=>:create_empty_record,:typeofrecord=>"Bride"}, :class=>"button-link" ,:id=>"new-bride", :remote=>true%>
   
    <p>
      </br>
      </br>
    </p>
      <%=render(:partial=>"bride_data_table") %>
  </div>
</div>

app/views/brides/new.html.erb
<h1>New Bride</h1>

<%= render 'form' %>

<%= link_to 'Back', brides_path %>

app/views/brides/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @bride.id %>
</p>

<p>
  <strong>User:</strong>
  <%= @bride.user_id %>
</p>

<p>
  <strong>Wedding date:</strong>
  <%= @bride.wedding_date %>
</p>

<p>
  <strong>Groom full name:</strong>
  <%= @bride.groom_full_name %>
</p>

<%= link_to 'Edit', edit_bride_path(@bride) %> |
<%= link_to 'Back', brides_path %>