config/routes.rb
Rails.application.routes.draw do
  
  resources :gift_registries do
    collection do
      get "create_empty_record"
      post "gift_registries_table"
      delete "delete" 
      
    end
  end
  
  resources :brides do
    collection do

      get "create_empty_record"
      post "bride_table"
      delete "delete" 
      post "update_gift_list"
      post "render_gift_section"
      post "update_gift_order"
      post "render_gift_list"
    end
  end
  
  resources :order_management do
    collection do
      get 'order_page'
      post 'add_to_order'
      get 'complete_order'
      put 'update_cart_item'
      post 'complete_order'
      get 'complete_order'
      post 'enter_order'
      get 'enter_order'
      get 'get_product_sub_totals'
      get 'delete_cart_item'
      get 'get_cart_contents'
    end
  end
  
  match "/site/show_my_gifts" => "site#show_my_gifts", via: :get
  match "/site/show_gifts" => "site#show_gifts", via: :get
  match "/site/update_cart_item" => "site#update_cart_item", via: :put
  match "/site/update_session" => "site#update_session", via: :put
  match "/site/find_bride" => "site#find_bride", via: :get
  match "/site/bride_active" => "site#bride_active", via: :get

  
end

app/models/gift_registry.rb
class GiftRegistry < ActiveRecord::Base
  belongs_to :product
  belongs_to :bride
  
   def self.reorder(id,position)
    puts(id, position)
    ActiveRecord::Base.connection.execute ("UPDATE `gift_registries` SET `position` = '"+position.to_s+"' WHERE `gift_registries`.`id` ="+id.to_s+" LIMIT 1 ;")
  end
  
   def true_quantity_reserved
     self.bride.order_items.where(:product_id => product_id).sum(:quantity)
   end
  
   def quantity_left
     return quantity_requested - true_quantity_reserved rescue 0
   end
   
end

app/controllers/gift_registries_controller.rb
class GiftRegistriesController < ApplicationController
  before_action :set_gift_registry, only: [:show, :edit, :update, :destroy]

  # GET /gift_registries
  def index
    @gift_registries = GiftRegistry.all
  end

  # GET /gift_registries/1
  def show
  end

  # GET /gift_registries/new
  def new
    @gift_registry = GiftRegistry.new
  end

  # GET /gift_registries/1/edit
  def edit
  end

  # POST /gift_registries
  def create
    @gift_registry = GiftRegistry.new(gift_registry_params)

    if @gift_registry.save
    redirect_to @gift_registry, notice: 'Gift registry was successfully created.'
  else
    render :new
  end
end
  
def create_empty_record
  @gift_registry = GiftRegistry.new()

  @gift_registry.bride_id = params[:bride_id]
  @gift_registry.quantity_reserved = 0
  @gift_registry.quantity_requested = 0
  @gift_registry.position = 999

  @gift_registry.product = Product.new
  @gift_registry.product.product_name="New Product"
  @gift_registry.product.product_description = "Edit Me."
  @gift_registry.product.unit_price = 0
  @gift_registry.product.msrp = 0
  @gift_registry.product.product_active=true;
  @gift_registry.product.save
  
    product_details = ProductDetail.new
    product_details.sku_active=true
    product_details.units_in_stock = 99999
    
    @gift_registry.product.product_details <<  product_details
    
    
  if @gift_registry.save
    respond_to do |format|
      format.html {redirect_to @gift_registry, notice: 'Gift was successfully created.' }
      format.json { render :json=> {:notice => 'Gift was successfully created.'} }
    end
  end
end

# PATCH/PUT /gift_registries/1
def update
    
  respond_to do |format|
    if @gift_registry.update(gift_registry_params)
      format.html { redirect_to(:action =>"edit", :notice => 'Gift was successfully updated.') }
      format.json { render :json=> {:notice => 'Gift was successfully updated.'} }
    else
      format.html { render :action => "edit" }
      format.json  { render :json => @gift_registry.errors, :status => :unprocessable_entity }
    end
  end
    
end

# DELETE /gift_registries/1
def destroy
  @gift_registry.destroy
    
  respond_to do |format|
    format.html { redirect_to gift_registries_url, notice: 'Gift registry was successfully deleted.' }
    format.json { head :ok }
    format.js { head :ok }
  end
end
  
  
 
private
# Use callbacks to share common setup or constraints between actions.
def set_gift_registry
  @gift_registry = GiftRegistry.find(params[:id])
end

# Only allow a trusted parameter "white list" through.
def gift_registry_params
  params.require(:gift_registry).permit(:id, :bride_id, :product_id, :quantity_requested, :quantity_reserved)
end
end

app/helpers/gift_registries_helper.rb
module GiftRegistriesHelper
end

app/views/gift_registries/_form.html.erb
<%= form_for(@gift_registry) do |f| %>
  <% if @gift_registry.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@gift_registry.errors.count, "error") %> prohibited this gift_registry from being saved:</h2>

      <ul>
      <% @gift_registry.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.number_field :id %>
  </div>
  <div class="field">
    <%= f.label :bride_id %><br>
    <%= f.number_field :bride_id %>
  </div>
  <div class="field">
    <%= f.label :product_id %><br>
    <%= f.number_field :product_id %>
  </div>
  <div class="field">
    <%= f.label :quantity_requested %><br>
    <%= f.number_field :quantity_requested %>
  </div>
  <div class="field">
    <%= f.label :quantity_reserved %><br>
    <%= f.number_field :quantity_reserved %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/gift_registries/edit.html.erb
<h1>Editing Gift Registry</h1>

<%= render 'form' %>

<%= link_to 'Show', @gift_registry %> |
<%= link_to 'Back', gift_registries_path %>

app/views/gift_registries/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Gift Registries</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Bride</th>
      <th>Product</th>
      <th>Quantity requested</th>
      <th>Quantity reserved</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gift_registries.each do |gift_registry| %>
      <tr>
        <td><%= gift_registry.id %></td>
        <td><%= gift_registry.bride_id %></td>
        <td><%= gift_registry.product_id %></td>
        <td><%= gift_registry.quantity_requested %></td>
        <td><%= gift_registry.quantity_reserved %></td>
        <td><%= link_to 'Show', gift_registry %></td>
        <td><%= link_to 'Edit', edit_gift_registry_path(gift_registry) %></td>
        <td><%= link_to 'Destroy', gift_registry, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift registry', new_gift_registry_path %>

app/views/gift_registries/new.html.erb
<h1>New Gift Registry</h1>

<%= render 'form' %>

<%= link_to 'Back', gift_registries_path %>

app/views/gift_registries/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @gift_registry.id %>
</p>

<p>
  <strong>Bride:</strong>
  <%= @gift_registry.bride_id %>
</p>

<p>
  <strong>Product:</strong>
  <%= @gift_registry.product_id %>
</p>

<p>
  <strong>Quantity requested:</strong>
  <%= @gift_registry.quantity_requested %>
</p>

<p>
  <strong>Quantity reserved:</strong>
  <%= @gift_registry.quantity_reserved %>
</p>

<%= link_to 'Edit', edit_gift_registry_path(@gift_registry) %> |
<%= link_to 'Back', gift_registries_path %>